<a href="https://colab.research.google.com/github/chunxu8894/tensorflow-tutorials/blob/master/TensorFlow_2_quickstart_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This tutorial is going to introduce how to use tensorflow to:


1.   Build a neural network that classifies images
2.   Train this neural network
3.   Evaluate the accuracy of the model



In [0]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0-rc2'

# 1. Loading the Data

In [0]:
# use the mnist dataset in keras
mnist = tf.keras.datasets.mnist

#split the dataset into 2 tuple
(x_train, y_train), (x_test, y_test)= mnist.load_data()

x_train, x_test = x_train/255.0, x_test/255.0


# 2. Build the model

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)]
)

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6101725 ,  0.17106853,  0.13894626, -0.22885898, -0.39672437,
        -0.12095048,  0.02380684,  0.8679477 ,  0.17257324, -0.62045306]],
      dtype=float32)

In [21]:
tf.nn.softmax(predictions).numpy()

array([[0.05241215, 0.11447764, 0.11085879, 0.07674222, 0.06488307,
        0.08548667, 0.09880199, 0.22981133, 0.11465002, 0.05187609]],
      dtype=float32)

# 3. Loss Function and Optimizer


In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [23]:
loss_fn(y_train[:1], predictions).numpy()

2.459395

In [0]:
model.compile(optimizer='adam', loss=loss_fn, metrics='accuracy') 

# 4. Fit Model


In [25]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2917 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1449 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1092 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0760 - accuracy: 0.9764


# 5. Model evaluate

In [29]:
model.evaluate(x_test, y_test, verbose=1)

313/313 [==============================] - 0s 1ms/step - loss: 0.0737 - accuracy: 0.9781


[0.07373541593551636, 0.9781000018119812]

The Image classifier is now trained to ~ 98% accuracy on this dataset

if you want your model to return a probability, you can wrap the trained model, and attach the softmax to it

In [0]:
probability_model = tf.keras.models.Sequential([
    model, 
    tf.keras.layers.Softmax()
])



In [31]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.30019276e-07, 1.64772884e-09, 2.77373624e-06, 4.17212897e-04,
        1.88412654e-11, 2.27295209e-06, 2.01418933e-13, 9.99574125e-01,
        1.17703371e-06, 2.10176222e-06],
       [1.95896419e-08, 2.78749053e-06, 9.99968767e-01, 2.74922950e-05,
        2.57170235e-15, 7.63615105e-07, 2.38852742e-08, 5.33553843e-12,
        2.22447312e-07, 6.73964973e-15],
       [5.17774765e-07, 9.98393118e-01, 9.44706189e-05, 4.08357155e-05,
        9.71004556e-05, 8.42929694e-06, 1.03496795e-05, 1.25105202e-03,
        1.03070059e-04, 9.06097455e-07],
       [9.99947548e-01, 7.36440353e-10, 4.16004550e-05, 2.79548829e-07,
        4.51502757e-07, 2.41111678e-07, 8.84881410e-06, 3.20849921e-07,
        5.45641976e-09, 6.97501491e-07],
       [1.60714771e-05, 6.48034126e-10, 1.16381370e-05, 4.51938709e-09,
        9.99702513e-01, 1.57263486e-07, 6.99766190e-07, 1.11075235e-04,
        8.84355302e-07, 1.56842245e-04]], dtype=float32)>

In [32]:
probability_model.compile(optimizer='adam', loss=loss_fn, metrics='accuracy')
probability_model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4902 - accuracy: 0.9766
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4862 - accuracy: 0.9790
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4834 - accuracy: 0.9810
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4824 - accuracy: 0.9810
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4805 - accuracy: 0.9834
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4793 - accuracy: 0.9839
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4786 - accuracy: 0.9848
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4781 - accuracy: 0.9845
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4763 - accuracy: 0.9863
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 1.476

In [33]:
probability_model.evaluate(x_test, y_test, verbose=1)

313/313 [==============================] - 0s 1ms/step - loss: 1.4813 - accuracy: 0.9806


[1.4812705516815186, 0.9805999994277954]